# We do not support Ubuntu < 14.04 in OpTiMSoC
# Unfortunately, travis does not support containerized builds in trusty
sudo: required
dist: trusty

# Install the build requirements
addons:
  apt:
    packages:
    - build-essential
    - tcl
    # for GLIP
    - libusb-1.0-0-dev
    # for GLIP TCP ("logic side")
    - libboost-dev
    # for the OSD software
    - libelf-dev
    - swig

language: python
python:
  # Python 3.4 is part of Ubuntu trusty, our lowest supported version
  - "3.4"

# Environment
env:
  global:
    # Installation target
    - TARGET_BASE=$HOME/optimsoc
    - PREBUILT_DEPLOY=optimsoc-prebuilt-deploy.py
    - PREBUILT_DEPLOY_URL=https://raw.githubusercontent.com/optimsoc/prebuilts/master/${PREBUILT_DEPLOY}

# Install dependencies
before_install:
  # dependency for fusesoc
  - pip install pyyaml

  # Create folder for target
  - mkdir -p ${TARGET_BASE}
  # Get prebuilts
  - curl ${PREBUILT_DEPLOY_URL} -o /tmp/${PREBUILT_DEPLOY}
  - chmod a+x /tmp/${PREBUILT_DEPLOY}
  - /tmp/${PREBUILT_DEPLOY} -d ${TARGET_BASE} all

# Execute the build and install it
install:
  - source ${TARGET_BASE}/setup_prebuilt.sh
  - ./tools/build.py --verbose --without-examples-fpga --with-examples-sim --without-docs
  - make install INSTALL_TARGET=${TARGET_BASE}/latest

# Test the build
script:
  - source ${TARGET_BASE}/latest/optimsoc-environment.sh
  - pytest -s -v test/systemtest/test_tutorial.py::TestTutorial
